# Generated by Django 4.1.7 on 2023-03-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default=True, max_length=30, null=True),
        ),
    ]
